# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Thoms
tagline:          Painting Vagabond
description:      Artist Website of a travelling Painter
url:              danielthoms.com
baseurl:          /

author:
  name:           Daniel Thoms
  url:            

paginate:         5
paginate_path:    blog/page:num/

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/danielthoms/danielthoms.github.io

gems: [jekyll-sitemap, jekyll-seo-tag]
